### PR TITLE
refactor/bump_ovos_holmes

### PR DESCRIPTION
**Pull request by JarbasAl**
now Holmes + ovos_utils allow setting the .conf file + XDG paths, we no longer need to monkey patch mycroft

### CODE REVIEW

**Comment by NeonDaniel** [comment]
@JarbasAl is this PR still valid?

**Comment by JarbasAl** [comment]
> @JarbasAl is this PR still valid?

no, need to update it, this is using the old approach before holmes.conf was introduced. Will update the PR

**Review by NeonDaniel — CHANGES_REQUESTED** [review]
I think this needs to be rebased, so I ignored any changes that appear to be from #141

**Comment by NeonDaniel** [comment]
Rebased and pushed to a separate branch to test https://github.com/NeonDaniel/NeonCore/runs/3819905900

```
ERROR: pip's legacy dependency resolver does not consider dependency conflicts when selecting packages. This behaviour is the source of the following dependency conflicts.
lingua-nostra 0.4.5 requires python-dateutil==2.6.0, but you'll have python-dateutil 2.8.2 which is incompatible.
```

locked dateutil in requirements.txt and re-ran: https://github.com/NeonDaniel/NeonCore/runs/3819960834?check_suite_focus=true

Dependency installation passed but unit tests failed

**Pull request merged**
